use crate::ddb::context::{ db_types, functions };
use crate::ddb::tables::{ Sheet, SheetMetaData };
use crate::ddb::DBLoad;
use crate::repository;
use crate::model;

use db_types::ToSqlValue;

pub async fn add_sheet_to_db_(
    new_sheet: model::NewSheetRequest,
    columns: Vec<model::NewSheetMetaDataRequest>,
    user_id: i32,
    model_file: Option<Vec<u8>>,
) -> anyhow::Result<()> {
    
    let mut chain_map = db_types::ChainMap::new();

    let mut sheet_insert_param = db_types::SqlMultipleParameters::new();
    sheet_insert_param.add_line(
        vec![
            (Sheet::COL_TABLE_NAME, new_sheet.table_name.to_sql_value()),
            (Sheet::COL_DESCRIPTION, new_sheet.description.to_sql_value()),
            (Sheet::COL_REQUEST_AFTER_UPDATE, new_sheet.request_after_update.to_sql_value()),
            (Sheet::COL_MODEL, model_file.to_sql_value()),
            (Sheet::COL_LAST_EDITED_BY_FK, user_id.to_sql_value()),
        ]
    );

    chain_map.push(&repository::sheet_insert, Some(sheet_insert_param), None);

    let mut meta_insert_param = db_types::SqlMultipleParameters::new();
    for column in columns {
        meta_insert_param.add_line(
            vec![
                (SheetMetaData::COL_DESCRIPTION,        column.description.to_sql_value()),
                (SheetMetaData::COL_COLUMN_NAME,        column.name.to_sql_value()),
                (SheetMetaData::COL_COLUMN_TYPE_FK,     column.column_type_fk.to_sql_value()),
                (SheetMetaData::COL_OPTIONAL,           column.optional.to_sql_value()),
                (SheetMetaData::COL_REGEX_CONSTRAINT,   column.regex_constraint.to_sql_value()),
                (SheetMetaData::COL_LAST_EDITED_BY_FK,  user_id.to_sql_value()),
            ]
        );
    }

    chain_map.push(&repository::sheet_meta_data_insert, Some(meta_insert_param), None);

    let a = functions::chain_executions(chain_map, db_types::SqlSingleParameters::new()).await?;

    Ok(())
}

pub async fn add_sheet_to_db(
    new_sheet: model::NewSheetRequest,
    columns: Vec<model::NewSheetMetaDataRequest>,
    user_id: i32,
    model_file: Option<Vec<u8>>,
) -> anyhow::Result<()> {
    let mut insert_parameters = db_types::SqlMultipleParameters::new();
    
    insert_parameters.add_line(
        vec![
            (Sheet::COL_TABLE_NAME,             new_sheet.table_name.to_sql_value()),
            (Sheet::COL_DESCRIPTION,            new_sheet.description.to_sql_value()),
            (Sheet::COL_REQUEST_AFTER_UPDATE,   new_sheet.request_after_update.to_sql_value()),
            (Sheet::COL_MODEL,                  model_file.to_sql_value()),
            (Sheet::COL_LAST_EDITED_BY_FK,      user_id.to_sql_value()),
        ]
    );

    let sheet_insert = functions::build_insert_clause(Sheet::TAB, &insert_parameters)?;

    let sheet_id = functions::get_identity(sheet_insert, Some(&insert_parameters.to_single()))
        .await?
        .ok_or_else(|| anyhow::anyhow!("No Id was generated by the insert in the Sheet table"))?;

    let mut insert_parameters = db_types::SqlMultipleParameters::new();

    for column in columns {
        insert_parameters.add_line(
            vec![
                (SheetMetaData::COL_SHEET_FK,           sheet_id.to_sql_value()),
                (SheetMetaData::COL_DESCRIPTION,        column.description.to_sql_value()),
                (SheetMetaData::COL_COLUMN_NAME,        column.name.to_sql_value()),
                (SheetMetaData::COL_COLUMN_TYPE_FK,     column.column_type_fk.to_sql_value()),
                (SheetMetaData::COL_OPTIONAL,           column.optional.to_sql_value()),
                (SheetMetaData::COL_REGEX_CONSTRAINT,   column.regex_constraint.to_sql_value()),
                (SheetMetaData::COL_LAST_EDITED_BY_FK,  user_id.to_sql_value()),
            ]
        );
    }

    let sheet_meta_insert = functions::build_insert_clause(SheetMetaData::TAB, &insert_parameters)?;

    let _ = functions::run_query(sheet_meta_insert, Some(&insert_parameters.to_single())).await?;

    Ok(())
}